server:
  port: 8090
spring:
  application:
    name: api-transactions
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/transactions_db
    username: root
    password: digital
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: wtjcofHqRcqmus9oOCDahU7MG9jv4GVP
    realm: spring
    serverUrl: http://localhost:9081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
maxAmount: 3000.0