server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: cuenta-service
          uri: lb://API-CUENTA
          predicates:
            - Path=/api-cuenta/**
        - id: transacciones-service
          uri: lb://API-TRANSACCIONES
          predicates:
            - Path=/api-transacciones/**
        - id: usuario-service
          uri: lb://API-USUARIO
          predicates:
            - Path=/api-usuario/**
        - id: cards-service
          uri: lb://API-CARDS
          predicates:
            - Path=/api-cards/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka