spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  security: # Add security configuration here
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
app:
  keycloak:
    realm: spring
    serverUrl: http://localhost:9081