spring:
  application:
    name: api-usuario
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
server:
  port: 8800
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: Y1jxfCXlaLYyVrUGOCfRpUB1Yv5lH4d7
    realm: spring
    serverUrl: http://localhost:9081

