server:
  port: 8085
spring:
  application:
    name: Cards
  datasource:
    #url: jdbc:mysql://localhost:3306/mscart
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/digitalMoneyHouse
    username: root
    password: digital
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mysql:
    console:
      enabled: true
  security:
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: Y1jxfCXlaLYyVrUGOCfRpUB1Yv5lH4d7
    realm: spring
    serverUrl: http://localhost:9081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka  # Your Eureka server URL
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10