server:
  port: 8089
spring:
  application:
    name: api-cuenta
  datasource:
    url: jdbc:mysql://localhost:3306/cuenta_db
    username: root
    password: digital
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
app:
  keycloak:
    admin:
      clientId: app-wallet
      clientSecret: gTYNs46PlfDQSdpYP5cvMNix2SC2Cz1f
    realm: spring
    serverUrl: http://localhost:9081